// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tuenti/go-netbox/netbox/models"
)

// IPAMVlansDeleteReader is a Reader for the IPAMVlansDelete structure.
type IPAMVlansDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPAMVlansDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewIPAMVlansDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewIPAMVlansDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIPAMVlansDeleteNoContent creates a IPAMVlansDeleteNoContent with default headers values
func NewIPAMVlansDeleteNoContent() *IPAMVlansDeleteNoContent {
	return &IPAMVlansDeleteNoContent{}
}

/*IPAMVlansDeleteNoContent handles this case with default header values.

IPAMVlansDeleteNoContent ipam vlans delete no content
*/
type IPAMVlansDeleteNoContent struct {
}

func (o *IPAMVlansDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/vlans/{id}/][%d] ipamVlansDeleteNoContent ", 204)
}

func (o *IPAMVlansDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewIPAMVlansDeleteNotFound creates a IPAMVlansDeleteNotFound with default headers values
func NewIPAMVlansDeleteNotFound() *IPAMVlansDeleteNotFound {
	return &IPAMVlansDeleteNotFound{}
}

/*IPAMVlansDeleteNotFound handles this case with default header values.

IPAMVlansDeleteNotFound ipam vlans delete not found
*/
type IPAMVlansDeleteNotFound struct {
	Payload *models.APIError
}

func (o *IPAMVlansDeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /ipam/vlans/{id}/][%d] ipamVlansDeleteNotFound  %+v", 404, o.Payload)
}

func (o *IPAMVlansDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
