// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tuenti/go-netbox/netbox/models"
)

// IPAMIPAddressesDeleteReader is a Reader for the IPAMIPAddressesDelete structure.
type IPAMIPAddressesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPAMIPAddressesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewIPAMIPAddressesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewIPAMIPAddressesDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIPAMIPAddressesDeleteNoContent creates a IPAMIPAddressesDeleteNoContent with default headers values
func NewIPAMIPAddressesDeleteNoContent() *IPAMIPAddressesDeleteNoContent {
	return &IPAMIPAddressesDeleteNoContent{}
}

/*IPAMIPAddressesDeleteNoContent handles this case with default header values.

IPAMIPAddressesDeleteNoContent ipam Ip addresses delete no content
*/
type IPAMIPAddressesDeleteNoContent struct {
}

func (o *IPAMIPAddressesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/ip-addresses/{id}/][%d] ipamIpAddressesDeleteNoContent ", 204)
}

func (o *IPAMIPAddressesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewIPAMIPAddressesDeleteNotFound creates a IPAMIPAddressesDeleteNotFound with default headers values
func NewIPAMIPAddressesDeleteNotFound() *IPAMIPAddressesDeleteNotFound {
	return &IPAMIPAddressesDeleteNotFound{}
}

/*IPAMIPAddressesDeleteNotFound handles this case with default header values.

IPAMIPAddressesDeleteNotFound ipam Ip addresses delete not found
*/
type IPAMIPAddressesDeleteNotFound struct {
	Payload *models.APIError
}

func (o *IPAMIPAddressesDeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /ipam/ip-addresses/{id}/][%d] ipamIpAddressesDeleteNotFound  %+v", 404, o.Payload)
}

func (o *IPAMIPAddressesDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
