// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/tuenti/go-netbox/netbox/models"
)

// IPAMVlansReadReader is a Reader for the IPAMVlansRead structure.
type IPAMVlansReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPAMVlansReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIPAMVlansReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewIPAMVlansReadNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIPAMVlansReadOK creates a IPAMVlansReadOK with default headers values
func NewIPAMVlansReadOK() *IPAMVlansReadOK {
	return &IPAMVlansReadOK{}
}

/*IPAMVlansReadOK handles this case with default header values.

IPAMVlansReadOK ipam vlans read o k
*/
type IPAMVlansReadOK struct {
	Payload *models.VLAN
}

func (o *IPAMVlansReadOK) Error() string {
	return fmt.Sprintf("[GET /ipam/vlans/{id}/][%d] ipamVlansReadOK  %+v", 200, o.Payload)
}

func (o *IPAMVlansReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VLAN)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIPAMVlansReadNotFound creates a IPAMVlansReadNotFound with default headers values
func NewIPAMVlansReadNotFound() *IPAMVlansReadNotFound {
	return &IPAMVlansReadNotFound{}
}

/*IPAMVlansReadNotFound handles this case with default header values.

IPAMVlansReadNotFound ipam vlans read not found
*/
type IPAMVlansReadNotFound struct {
	Payload *models.APIError
}

func (o *IPAMVlansReadNotFound) Error() string {
	return fmt.Sprintf("[GET /ipam/vlans/{id}/][%d] ipamVlansReadNotFound  %+v", 404, o.Payload)
}

func (o *IPAMVlansReadNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
